services:
  - type: web
    name: your-app-name
    env: python
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    plan: free
    branch: main
    autoDeploy: true
    healthCheckPath: /_stcore/health
